name: Run Python

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run program
        run: python3 main.py

      - name: Prepare SSH
        if: github.event_name == 'push'
        run: |
          test -n "$SSH_PRIVATE_KEY" || {
            echo "SSH_PRIVATE_KEY is empty"
            exit 1
          }

          install -m 700 -d ~/.ssh

          printf '%s\n' "$SSH_PRIVATE_KEY" \
            | tr -d '\r' \
            > ~/.ssh/id_ed25519

          chmod 600 ~/.ssh/id_ed25519

          ssh-keygen -y \
            -f ~/.ssh/id_ed25519 \
            > /dev/null

          ssh-keyscan -H 178.128.22.26 \
            >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy file
        if: github.event_name == 'push'
        run: |
          scp \
            -i ~/.ssh/id_ed25519 \
            -o IdentitiesOnly=yes \
            main.py \
            submission@178.128.22.26:/home/submission/deploy/